# Generated by Django 5.2.10 on 2026-03-22 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_address_cart_category_order_payment_product_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='parent',
        ),
        migrations.AddField(
            model_name='category',
            name='images',
            field=models.ImageField(default=1, upload_to='products/'),
            preserve_default=False,
        ),
    ]
