# Generated by Django 5.2.10 on 2026-04-05 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_rename_images_productimage_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='customeuser',
            name='is_mobile_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customeuser',
            name='mobile',
            field=models.CharField(default=1, max_length=15, unique=True),
            preserve_default=False,
        ),
    ]
