# Generated by Django 5.2.10 on 2026-04-05 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0008_otp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='otp',
            name='mobile',
        ),
        migrations.AddField(
            model_name='otp',
            name='email',
            field=models.EmailField(default=1, max_length=254),
            preserve_default=False,
        ),
    ]
