# Generated by Django 5.2.10 on 2026-04-05 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0010_delete_otp_customeuser_email_otp_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customeuser',
            name='reset_otp',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='customeuser',
            name='reset_otp_created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
